# Numpy Broadcasting Practice

Numpy has broadcasting features to map one array to another.  This is to practice and work out examples.

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
arr + 4

array([4, 5, 6, 7, 8])

In [5]:
a1 = np.random.randn(4, 3)

In [6]:
a1

array([[-0.06808797, -0.107609  ,  0.59657581],
       [ 1.37661299, -1.62512836, -0.28166268],
       [-0.76390104,  0.26519038,  0.8986044 ],
       [-0.75504703,  0.57571108,  2.3388972 ]])

In [7]:
a1.mean()

0.20417964742060532

In [9]:
a1 - a1.mean()

array([[-0.27226762, -0.31178865,  0.39239616],
       [ 1.17243334, -1.82930801, -0.48584232],
       [-0.96808068,  0.06101073,  0.69442475],
       [-0.95922668,  0.37153143,  2.13471755]])

In [12]:
a1[0].mean()

0.14029294561778974

In [13]:
a1 - a1[0].mean()

array([[-0.20838092, -0.24790195,  0.45628287],
       [ 1.23632004, -1.76542131, -0.42195562],
       [-0.90419398,  0.12489743,  0.75831145],
       [-0.89533998,  0.43541813,  2.19860425]])